import { OptionNetworkType } from "@/types/types";

export const LIST_LINK: Array<OptionNetworkType> = [
  {
    name: "Ethereum",
    id: "eth",
    image: "/svg/network/ethIcon.svg",
    symbol: "ETH",
    slug: "ethereum",
    slugDextool: "ether",
    isSupport: true,
    chain: "1",
    IdMoralis: "0x1",
  },

  {
    name: "Solana",
    id: "solana",
    slug: "solana",
    slugDextool: "solana",
    image: "/svg/network/solanaIcon.svg",
    symbol: "SOL",
    isSupport: true,
    IdMoralis: "solana",
  },
  {
    name: "BSC",
    id: "bsc",
    slugDextool: "bsc",
    slug: "bsc",
    chain: "56",
    image: "/svg/network/bnbIcon.svg",
    symbol: "BNB",
    isSupport: true,
    IdMoralis: "0x38",
  },
  {
    name: "Base",
    id: "base",
    slug: "base",
    slugDextool: "base",
    chain: "8453",
    image: "/svg/network/base.svg",
    symbol: "WETH",
    isSupport: true,
    IdMoralis: "0x2105",
  },
  {
    name: "Arbitrum",
    id: "arbitrum",
    slugDextool: "arbitrum",
    image: "/svg/network/arbIcon.svg",
    symbol: "WETH",
    isSupport: true,
    slug: "arbitrum",
    chain: "42161",
    IdMoralis: "0xa4b1",
  },
  {
    name: "Avalanche",
    id: "avax",
    slug: "avalanche",
    slugDextool: "avalanche",
    image: "/svg/network/avanIcon.svg",
    symbol: "AVAX",
    isSupport: true,
    chain: "43114",
    IdMoralis: "0xa86a",
  },
  {
    name: "Polygon",
    id: "polygon_pos",
    slug: "polygon",
    slugDextool: "polygon",
    image: "/svg/network/polyIcon.svg",
    symbol: "MATIC",
    isSupport: true,
    chain: "137",
    IdMoralis: "0x89",
  },

  {
    name: "Optimism",
    id: "optimism",
    slug: "optimism",
    slugDextool: "optimism",
    image: "/svg/network/op.svg",
    symbol: "WETH",
    isSupport: true,
    chain: "10",
    IdMoralis: "0xa",
  },

  {
    name: "Blast",
    id: "blast",
    slug: "blast",
    slugDextool: "blast",
    image: "/svg/network/blast.webp",
    symbol: "WETH",
    isSupport: true,
  },
  {
    name: "zkSync",
    id: "zksync",
    slug: "zksync",
    chain: "324",
    isSupport: true,
    image: "/svg/network/zksync.svg",
    symbol: "ETH",
    IdMoralis: "0x2000",
  },
  {
    name: "Injective",
    id: "injective",
    slug: "injective",
    image: "/svg/network/injective.webp",
    symbol: "INJ",
    isSupport: true,
  },
  {
    name: "PulseChain",
    id: "pulsechain",
    slug: "pulsechain",
    image: "/svg/network/pulsechain.png",
    symbol: "WETH",
    isSupport: true,
    IdMoralis: "0x171",
  },
  {
    name: "Mantle",
    id: "mantle",
    slug: "mantle",
    image: "/svg/network/mantle.png",
    symbol: "WMNT",
    isSupport: true,
  },
  {
    name: "Klaytn",
    id: "klaytn",
    slug: "klaytn",
    image: "/svg/network/klaytn.png",
    symbol: " WKLAY",
    isSupport: true,
  },
  {
    name: "Osmosis",
    id: "osmosis",
    slug: "osmosis",
    image: "/svg/network/osmosis.svg",
    symbol: " OSMD",
    isSupport: true,
  },
  {
    name: "Canto",
    id: "canto",
    slug: "canto",
    isSupport: true,
    image: "/svg/network/canto.png",
    symbol: "WCANTO",
  },
  {
    name: "Astar",
    id: "astr",
    isSupport: true,
    slug: "astar",
    image: "/svg/network/astar.png",
    symbol: "WASTR",
  },
  {
    name: "Linea",
    id: "linea",
    slug: "linea",
    isSupport: true,
    image: "/svg/network/linea.svg",
    symbol: "WPLS",
    chain: "59144",
    IdMoralis: "0xe708",
  },
  {
    name: "Cronos",
    id: "cro",
    slug: "cronos",
    image: "/svg/network/cronos.png",
    symbol: "CRO",
    isSupport: true,
    chain: "25",
  },
  {
    name: "Metis",
    id: "metis",
    slug: "metis",
    isSupport: true,
    image: "/svg/network/metis.png",
    symbol: "METIS",
  },
  {
    name: "Fantom",
    id: "ftm",
    slug: "fantom",
    chain: "250",
    image: "/svg/network/fantomIcon.svg",
    symbol: "FTM",
    isSupport: true,
  },
  {
    name: "Moonbeam",
    id: "glmr",
    slug: "moonbeam",
    isSupport: true,
    image: "/svg/network/moonbeam.png",
    symbol: "WGLMR",
  },
  {
    name: "Sui",
    id: "sui",
    slug: "sui",
    isSupport: true,
    image: "/svg/network/sui.svg",
    symbol: "sui",
  },
  {
    name: "Aptos",
    id: "aptos",
    slug: "aptos",
    isSupport: true,
    image: "/svg/network/aptos.png",
    symbol: "APT",
  },
  {
    name: "Manta",
    id: "manta",
    slug: "manta",
    isSupport: true,
    image: "/svg/network/manta.webp",
    symbol: "ETH",
  },
  {
    name: "Hedera",
    id: "hedera",
    slug: "hedera",
    image: "/svg/network/hedera.webp",
    symbol: "HBAR",
    isSupport: true,
  },
  {
    name: "Avalanche DFK",
    id: "avalanchedfk",
    slug: "avalanchedfk",
    isSupport: true,
    image: "/svg/network/avanIcon.svg",
    symbol: "WJEWEL",
  },
  {
    name: "Scroll",
    id: "scroll",
    slug: "scroll",
    chain: "534352",
    image: "/svg/network/scroll.svg",
    symbol: "ETH",
    isSupport: true,
  },
  {
    name: "Celo",
    id: "celo",
    slug: "celo",
    isSupport: true,
    image: "/svg/network/celoIcon.svg",
    symbol: "CELO",
  },
  {
    name: "Kava",
    id: "kava",
    slug: "kava",
    image: "/svg/network/kava.png",
    symbol: "WKAVA",
    isSupport: true,
  },
  {
    name: "NEAR",
    id: "near",
    slug: "near",
    image: "/svg/network/near.svg",
    symbol: "NEAR",
    isSupport: true,
  },
  {
    name: "opBNB",
    id: "opbnb",
    slug: "opbnb",
    chain: "204",
    image: "/svg/network/opbnb.png",
    symbol: "BNB",
    isSupport: true,
  },
  {
    name: "Core",
    id: "core",
    slug: "core",
    image: "/svg/network/coredao.png",
    symbol: "WCORE",
    isSupport: true,
  },
  {
    name: "Polygon zkEVM",
    id: "polygon-zkevm",
    slug: "polygonzkevm",
    image: "/svg/network/polygonzkevm.png",
    symbol: "WETH",
    isSupport: true,
  },
  {
    name: "IoTeX",
    id: "iotex",
    slug: "iotex",
    image: "/svg/network/iotex.png",
    symbol: "WIOTX",
    isSupport: true,
  },
  {
    name: "Evmos",
    id: "evmos",
    slug: "evmos",
    isSupport: true,
    image: "/svg/network/evmos.png",
    symbol: "WEVMOS",
  },
  {
    name: "Aurora",
    id: "aurora",
    slug: "aurora",
    image: "/svg/network/aurora.png",
    symbol: "NEAR",
    isSupport: true,
  },
  {
    name: "Conflux",
    id: "cfx",
    slug: "conflux",
    image: "/svg/network/conflux.png",
    symbol: "WCFX",
    isSupport: true,
  },
  {
    name: "Wanchain",
    id: "wan",
    slug: "wanchain",
    image: "/svg/network/wan.png",
    symbol: "WWAN",
    isSupport: true,
  },
  {
    name: "Gnosis Chain",
    id: "gnosischain",
    slug: "gnosischain",
    image: "/svg/network/gnosis.png",
    symbol: "WXDAI",
    isSupport: true,
    chain: "100",
  },
  {
    name: "Arbitrum Nova",
    id: "arbitrum_nova",
    slug: "arbitrumnova",
    image: "/svg/network/arbitrumnova.png",
    symbol: "WETH",
    isSupport: true,
  },
  {
    name: "Ethereum Classic",
    id: "ethereum_classic",
    slug: "ethereumclassic",
    image: "/svg/network/etc.png",
    symbol: "WETC",
    isSupport: true,
  },
  {
    name: "Acala",
    id: "acala",
    slug: "acala",
    image: "/svg/network/acala.svg",
    symbol: "ACA",
    isSupport: true,
  },
  {
    name: "Dogechain",
    id: "dogechain",
    slug: "dogechain",
    image: "/svg/network/dogechain.png",
    symbol: "WWDOGE",
    isSupport: true,
  },
  {
    name: "Harmony",
    id: "one",
    slug: "harmony",
    image: "/svg/network/harmony.png",
    symbol: "WONE",
    isSupport: true,
  },
  {
    name: "Telos",
    id: "tlos",
    slug: "telos",
    image: "/svg/network/telos.png",
    symbol: "WTLOS",
    isSupport: true,
  },
  {
    name: "KCC",
    id: "kcc",
    slug: "kcc",
    chain: "321",
    image: "/svg/network/kucoin.png",
    symbol: "WKCS",
    isSupport: true,
  },
  {
    name: "Velas",
    id: "velas",
    slug: "velas",
    image: "/svg/network/velas.png",
    symbol: "VLX",
    isSupport: true,
  },
  {
    name: "Tomb Chain",
    id: "tombchain",
    slug: "tombchain",
    image: "/svg/network/tomb.png",
    symbol: "WWAN",
    isSupport: true,
  },
  {
    name: "HECO",
    id: "heco",
    slug: "heco",
    image: "/svg/network/heco.svg",
    symbol: "WHT",
    isSupport: true,
    chain: "128",
  },
  {
    name: "Moonriver",
    id: "movr",
    slug: "moonriver",
    image: "/svg/network/moonriver.png",
    symbol: "WMOVR",
    isSupport: true,
  },
  {
    name: "Boba",
    id: "boba",
    slug: "boba",
    image: "/svg/network/boba.png",
    symbol: "BOBA",
    isSupport: true,
  },
  {
    name: "Oasis Emerald",
    id: "oasis",
    slug: "oasisemerald",
    image: "/svg/network/osmosis.svg",
    symbol: "ROSE",
    isSupport: true,
  },
  {
    name: "Fuse",
    id: "fuse",
    slug: "fuse",
    image: "/svg/network/fuse.svg",
    symbol: "WFUSE",
    isSupport: true,
  },
  {
    name: "ThunderCore",
    id: "thundercore",
    slug: "thundercore",
    image: "/svg/network/thundercore.png",
    symbol: "WTT",
    isSupport: true,
  },
  {
    name: "Step Network",
    id: "step-network",
    slug: "stepnetwork",
    image: "/svg/network/stepnetwork.png",
    symbol: "FITFI",
    isSupport: true,
  },
  {
    name: "Filecoin",
    id: "filecoin",
    slug: "filecoin",
    image: "/svg/network/filecoin.png",
    symbol: "WFIL",
    isSupport: true,
  },
  {
    name: "OKC",
    id: "okc",
    slug: "okc",
    image: "/svg/network/oec.png",
    symbol: "WOKT",
    isSupport: true,
  },
  {
    name: "Meter",
    id: "mtr",
    slug: "meter",
    image: "/svg/network/meter.png",
    symbol: "MTGR",
    isSupport: true,
  },
  {
    name: "Goerli",
    id: "goerli",
    slug: "goerli",
    image: "/svg/network/ether_goerli.png",
    symbol: "GETH",
    isSupport: true,
  },
  {
    name: "Godwoken",
    id: "godwoken",
    slug: "godwoken",
    image: "/svg/network/godwoken.svg",
    symbol: "pCKB",
    isSupport: true,
  },
  {
    name: "Milkomeda",
    id: "milkada",
    slug: "milkomedacardano",
    image: "/svg/network/milkomeda.png",
    symbol: "WADA",
    isSupport: true,
  },
  {
    name: "Shibarium",
    id: "shibarium",
    slug: "shibarium",
    image: "/svg/network/shibarium.png",
    symbol: "BONE",
    isSupport: true,
  },
  {
    name: "KardiaChain",
    id: "kardiachain",
    slug: "kardiachain",
    image: "/svg/network/kardia.png",
    symbol: "WKAI",
    isSupport: true,
  },
  {
    name: "SmartBCH",
    id: "bch",
    slug: "smartbch",
    image: "/svg/network/smartbch.png",
    symbol: "WBCH",
    isSupport: true,
  },
  {
    name: "Elastos",
    id: "ela",
    slug: "elastos",
    image: "/svg/network/elastos.png",
    symbol: "WELA",
    isSupport: true,
  },
  {
    name: "SX Network",
    id: "sxn",
    slug: "sxnetwork",
    image: "/svg/network/sx.png",
    symbol: "WSX",
    isSupport: true,
  },
  {
    name: "EthereumPoW",
    id: "ethereumpow",
    slug: "ethereumpow",

    image: "/svg/network/ethw.png",
    symbol: "WETH",
    isSupport: true,
  },
  {
    name: "Syscoin",
    id: "sys",
    slug: "syscoin",

    image: "/svg/network/syscoin.png",
    symbol: "WSYS",
    isSupport: true,
  },
  {
    name: "Energi",
    id: "nrg",
    slug: "energi",

    image: "/svg/network/energi.png",
    symbol: "WNGR",
    isSupport: true,
  },
  {
    name: "Bitgert",
    id: "bitgert",
    slug: "bitgert",

    image: "/svg/network/bitgert.png",
    symbol: "WBRISE",
    isSupport: true,
  },
  {
    name: "Alvey",
    id: "alvey",
    slug: "alvey",
    image: "/svg/network/alvey.png",
    symbol: "ALV",
    isSupport: true,
  },
  {
    name: "Loop Network",
    id: "loop-network",
    slug: "loopnetwork",
    image: "/svg/network/loopnetwork.webp",
    symbol: "LOOP",
    isSupport: true,
  },
  {
    name: "Redlight Chain",
    id: "redlight_chain",
    slug: "redlightchain",
    image: "/svg/network/redlight.png",
    symbol: "WREDLC",
    isSupport: true,
  },

  {
    name: "EthereumFair",
    id: "ethereumfair",
    slug: "ethereumfair",
    image: "/svg/network/ethf.png",
    symbol: "WETH",
    isSupport: true,
  },
  {
    name: "starknet",
    id: "strk",
    image: "/svg/network/starknet.png",
    symbol: "STRK",
    slug: "starknet",
    slugDextool: "starknet",
    isSupport: true,
  },
  {
    name: "Ton",
    id: "ton",
    image: "/svg/network/ton.webp",
    symbol: "ton",
    slug: "ton",
    slugDextool: "ton",
    isSupport: true,
  },
];

export const LIST_CHAIN = [
  // {
  //   id: '66',
  //   name: 'okc',
  //   label: 'OKC',
  //   img: '/svg/network/ok.svg',
  // },
  // {
  //   id: '10001',
  //   name: 'ethw',
  //   label: 'ETHW',
  //   img: '/svg/network/ethw.svg',
  // },
  // {
  //   id: '201022',
  //   name: 'fon',
  //   label: 'FON',
  //   img: '/svg/network/fon.svg',
  // },
  // {
  //   id: 'tron',
  //   name: 'tron',
  //   label: 'Tron',
  //   img: '/svg/network/tronIcon.svg',
  // },
];
